# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Output Data                                                         #
# ------------------------------------------------------------------------------------------------------------------------- #

output_folder: backmapped/A2A/atomistic/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_folder: mappings_hierarchical_protein
structure_filename: /storage_common/angiod/A2A/tpr/a2a.tpr             # Supported formats: [top, pdb, gro, psf, tpr]
traj_filenames:                                                        # Supported formats: [trr, xtc]
  - /storage_common/angiod/A2A/trr/a2a.trr
simulation_is_cg: false
selection: protein

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:0

# ------------------------------------------------------------------------------------------------------------------------- #
# --- If you want to load a deployed model, provide its filename to the 'model' parameter --------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------- #

# OPTION 1 - Load deployed model
model: deployed/A2A.pth

# ------------------------------------------------------------------------------------------------------------------------- #
# --- If you want to load your own trained model, provide the 'model_training_config_file' parameter, which specifies the - #
# --- config file used for training. Optionally, you can specify the 'model_relative_weights' parameter as well. ---------- #
# ------------------------------------------------------------------------------------------------------------------------- #

# OPTION 2 - Load a model from your training session
# model_training_config_file: config/training/A2A.yaml
# model_relative_weights: best_model.pth

# ------------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Backmapping Backbone                                                     #
# ------------------------------------------------------------------------------------------------------------------------- #

bb_minimisation_dtau: 1.e-1
bb_initial_minimisation_eps: 1.e-2
bb_minimisation_eps:  1.e-3
# trace_every: 10