# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Output Data                                                         #
# ------------------------------------------------------------------------------------------------------------------------- #

output_folder: backmapped/PED/atomistic/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_folder: mappings_hierarchical_protein
structure_filename: /storage_common/angiod/PED/pdb/test/PED00055e000.pdb      # Supported formats: [top, pdb, gro, psf, tpr]
simulation_is_cg: false
selection: protein

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:0
model_config_file: config/training/PED.yaml
model_relative_weights: best_model.pth

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Backmapping Backbone                                                     #
# ------------------------------------------------------------------------------------------------------------------------- #

bb_minimisation_dtau: 1.e-1
bb_initial_minimisation_eps: 1.e-2
bb_minimisation_eps:  1.e-3