# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Experiment Metadata                                                      #
# ------------------------------------------------------------------------------------------------------------------------- #

name: PED00055
output_folder: backmapped/PED/atomistic/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_root: ./heqbm/data/mappings_hierarchical_protein
structure_filename: /storage_common/angiod/PED/pdb/test/PED00055e000.pdb      # Supported formats: [top, pdb, gro, psf, tpr]
max_bead_atoms: 5
selection: protein

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:0
model_config_file: config/training/PED.yaml
model_relative_weights: best_model.pth

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                  Backmapping Backbone                                                     #
# ------------------------------------------------------------------------------------------------------------------------- #

bb_minimization_dtau: 1.e-1
bb_minimization_eps:  1.e-4