# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Output Data                                                         #
# ------------------------------------------------------------------------------------------------------------------------- #

output_folder: backmapped/ZMA/atomistic/

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                       Input Data                                                          #
# ------------------------------------------------------------------------------------------------------------------------- #

mapping_folder: mappings_hierarchical_zma
structure_filename: /storage_common/angiod/LIGANDS/ZMA/atomistic/zma.gro      # Supported formats: [top, pdb, gro, psf, tpr]
traj_filenames:                                                               # Supported formats: [trr, xtc]
  - /storage_common/angiod/LIGANDS/ZMA/atomistic/zma_nopbc.xtc
simulation_is_cg: false

# ------------------------------------------------------------------------------------------------------------------------- #
#                                                Backmapping Model Config                                                   #
# ------------------------------------------------------------------------------------------------------------------------- #

model_device: cuda:0
model_config_file: config/training/ZMA.yaml
model_relative_weights: best_model.pth